### ISSUE TITLE
Enhanced attribution

### ISSUE THREAD

**Issue by chhamilton** [WICG/performance-measure-memory#14]
I was thinking about how to make this API more actionable for developers. Since URLs are in general quite dynamic, I thought it might also be useful to provide the "id" of the iframe, instead of just its src URL:

attribution: [ { "id": "iframeFoo", "src": "https://a.com" } ]

Combined with detached context tracking it could help diagnose unintentional leaks, by seeing multiple attributions to the same element ID.

It might also be useful to know something about the frame-tree if cross-origin aggregation is occurring in an attribution context. This information is already available to the embedder (the frame tree) so isn't a leak. We could simply indicate the "size" of the frame tree that is being aggregated somehow? Or the entire frame-tree topology, along with memory per node?

**Comment by ulan** [comment]
Thanks! I like the idea about providing the id of the iframe. Since the id may change, I guess the spec should allow the implementation to return any id of the iframe.

Do you mean the frame-tree inside a cross-origin iframe? I think that is not available to the parent frame. Otherwise, the parent frame could figure out what is happening inside a cross-origin iframe. I think the most we can do without leaking info is to have a boolean field that says "this entry may aggregate other iframes " and set it to true for all cross-origin iframes.

**Comment by chhamilton** [comment]
No, it turns out that even for cross-origin iframes, any frame can navigate the frame tree via window.frames, and window.parent. So in fact, it's possible for any frame to know the entire topology of the frame tree. Maybe the attribution could actually have the same layout as the topology, and only reports URLs and ids if that information is same-origin?

**Comment by domenic** [comment]
> any frame can navigate the frame tree via window.frames, and window.parent.

This is true. More specifically, they can call `window.parent.location.href = ...`

> So in fact, it's possible for any frame to know the entire topology of the frame tree.

I don't believe this is true. In particular, the getter, `window.parent.location.href`, does not work.

This fits with the general legacy cross-origin access principle that writing is allowed but not reading. (Similar things are done with canvas tainting, for example.)

**Comment by domenic** [comment]
Upon re-reading, I see that I misinterpreted what you were saying. You were strictly talking about the topology, i.e. the tree structure. I thought you also meant the URLs of things in the tree, but you were clear to specify that you'd only expose those same-origin.

Sorry for the noise!

**Comment by ulan** [comment]
I didn't know that the frame tree is exposed cross-origin. Thanks!

We checked with GSuite folks. They said that a iframe id would be useful. The frame tree topology not so much, because they already know the topology and recording it might be cumbersome. Besides that, browsers that can only do coarse-grained attribution (e.g. per agent or per-process) would need a way to group iframes for reporting, which is tricky to do with topology format.

I will add the id attribute to the spec.

**Comment by ulan** [comment]
Fixed in the spec and explainer. Each element in the attribution now provides the URL and the container attributes:
```
attribution: [
        {
          url: "https://example.com/iframe.html"
          container: {
            id: "example-id",
            src: "redirect.html?target=iframe.html",
          },
          scope: "Window",
        }
      ],
```
