### ISSUE TITLE
What is the scope for shared/service workers

### ISSUE THREAD

**Issue by annevk** [WICG/performance-measure-memory#4]
You say the scope is all agent clusters of a browsing context group, but shared/service workers have their own agent clusters in their own scope and while they do have COEP (and that should be required), there's no real cross-site thing going on there (and they should also not end up in the browsing context group).

**Comment by ulan** [comment]
Good point! I had this misconception that service/shared workers are part of the browsing context group while writing this proposal. Few days ago I tried to fixed that by adding _"... browsing context group including shared resources such as ServiceWorkers, SharedWorkers, SharedArrayBuffers."_ but I see that I missed one place.

The intention is to include shared/service workers. I think it is important. Otherwise it would be misleading for the developers and would send a signal that shared/service workers are better for memory.

Is there a standard concept that captures _all agent clusters of the browsing context group + all the used shared/service workers_?

It would be great to make the definition in the proposal more formal and precise.

**Comment by annevk** [comment]
If you do it transitive than the scope is the user agent, since those agent clusters might have references to other browsing context groups. I'm not sure that's a great model however and seems like it would introduce way too many side channels.

**Comment by ulan** [comment]
I am looking for something between "user agent" and "browsing context group".

The memory measurement should stop at shared/service workers. Including other browsing contexts doesn't provide useful data for the developers and indeed complicates the security story.

**Comment by annevk** [comment]
I think I need a more detailed design description to give an adequate answer.

**Comment by domenic** [comment]
@ulan and I discussed this a bit offline and we think it might be better to separate out service and shared workers. That is, when you use this API in a Window context, it includes only agent clusters of the current BCG (so windows and dedicated workers owned by them). Then, you separately need to use this API inside your shared workers or service workers, and that would give you memory measurement for those shared/service workers (plus any nested dedicated workers).

Although this aligns better with the spec and implementation architecture, I think it may be slightly less user-friendly for web developers. In particular, unlike us spec/implementation people, I'm not sure web developers have the same mental model that the "top level entities" are top-level Windows, shared workers, and service workers. I suspect web developers think of shared/service workers as somewhat belonging to their associated windows, even if logically this doesn't make sense. And this may lead to some confusion where web developers think that by using this API in a top-level window, they're getting all the relevant information, without realizing they need to use it in their service workers and shared workers as well.

But, in my opinion this is an OK tradeoff to make. In the end, developers using this API need some level of sophistication, and asking that they understand what the top-level entities are in their web app seems like a reasonable ask.

**Comment by ulan** [comment]
Fixed by the commits above.
